const UNSAVED_CONSTANTS = {
  ACTION: {
    UNSAVED_ACTIVE: 'UNSAVED_ACTIVE',
    GET_UNSAVED_STATE: 'GET_UNSAVED_STATE',
    MODAL_ACTIVE: 'MODAL_ACTIVE',
    AFTER_CONFIRM: 'AFTER_CONFIRM',
  },
};

export default UNSAVED_CONSTANTS;
